# Generated by Django 4.0 on 2022-01-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В процессе'), ('done', 'Сделано')], default='new', max_length=11, verbose_name='Статус')),
                ('description', models.TextField(max_length=2000, verbose_name='Описание')),
                ('date_of_completion', models.DateField(null=True, verbose_name='Дата выполнения')),
            ],
        ),
    ]
